sulfur:
  - name: "Mongo to BQ"
    cron: "1 * * * *"
    truncate: false
    transform:
      file: './transform.py'
      fn: 'advanced_transform'
    source:
      name: "emre"
      type: "Mongo"
      host: "127.0.0.1"
      port: "27017"
      auth:
        username: ""
        password: ""
      database: "new_db"
      collection: "ffff"
    destination:
      name: "emre"
      type: "redis"
      host: "redis://127.0.0.1"
      key: "yeniii"