sulfur:
  - name: "Mongo to BQ"
    cron: "1 * * * *"
    destination:
      name: "emre"
      type: "Mongo"
      host: "mongodb://127.0.0.1/"
      port: "27017"
      user: "test"
      password: "test"
      database: "yeni_db"
      collection: "testt_etmek"
    source:
      name: "emre"
      type: "redis"
      host: "redis://127.0.0.1"
      key: "hoba"